### PR TITLE
fixed manageSubscriptions where it should call manageSubscription

### PR DESCRIPTION
**Pull request by k0shk0sh**
instead of manageViewSubscription in RxTiPresenterSubscriptionHandler

### CODE REVIEW

**Comment by StefMa** [comment]
Oh wow!
Nice catch. Thank you 👍 

Can you please add a test so that something like that will never happen again?!
You can simple copy tests like [this](https://github.com/grandcentrix/ThirtyInch/blob/master/rx/src/test/java/net/grandcentrix/thirtyinch/rx/RxTiPresenterSubscriptionHandlerTest.java#L192) but called `manageSubscriptions`.

**Comment by k0shk0sh** [comment]
@StefMa sure, I'll write up that right now.

**Comment by k0shk0sh** [comment]
@StefMa didn't want to introduce something new, so I followed up `manageSusbription` tests.

**Comment by passsy** [comment]
Ouch, that was a good catch!

**Comment by passsy** [comment]
@StefMa please add a test for [RxTiPresenterDisposableHandler#manageDisposables(Disposable...)](https://github.com/grandcentrix/ThirtyInch/blob/master/rx2/src/main/java/net/grandcentrix/thirtyinch/rx2/RxTiPresenterDisposableHandler.java#L84)

**Pull request merged**
