### PR TITLE
Add retrolambda to the sample app

### PR DESCRIPTION
**Pull request by jonathan-caryl**
Adding retrolambda makes for more compact and easier to read code when
used with RxJava

### CODE REVIEW

**Comment by StefMa** [comment]
Don't know if I like that Idea 🤔
Samples are here to understand the simplest use case of an implementation.
Unfortunately not all developers are similar with lambdas yet (and but
true, I know).

However. If we add something like that I recommend to add it with the
official implementation of android (have never used it,so don't know if it
will work with our sample).

Anyway what do you say @passsy?

**Comment by jonathan-caryl** [comment]
You could say that not all developers are familiar with RxJava yet either...

**Comment by passsy** [comment]
I'm fine with using lambdas in the sample. However, we should not integrate retrolambda and use the jack compiler instead.

**Comment by jonathan-caryl** [comment]
I've not used the jack compiler yet. I'll see if I can figure that out & update the PR.

**Comment by jonathan-caryl** [comment]
Looks like using Jack is now pretty simple. PR updated.

**Comment by vRallev** [comment]
Note that Jack is much slower than RetroLamba. But that's probably not a big deal for this sample.

**Comment by StefMa** [comment]
I've noticed it as well @vRallev .
But as you said. It is an sample ;)

If I clean the project and run it it cost me round about 35 secs.
If I change something in the code it builds in round about 2 secs.

I guess that is enough.

Thank you @jonathan-caryl for the PR 👍

**Comment by passsy** [comment]
travis hangs at `:sample:transformClassesWithPreJackRuntimeLibrariesForDebug` 😒

**Comment by jonathan-caryl** [comment]
[SO](http://stackoverflow.com/a/41664491/1789683) suggests this may be solved by bumping up the heap size for dex-ing. Let's give that a go...

**Comment by jonathan-caryl** [comment]
Back to retrolambda

**Comment by StefMa** [comment]
You have merged a broken build 🤣

**Comment by passsy** [comment]
travis was fine, only codecov wasn't happy

**Pull request merged**
