### PR TITLE
Upgrade gradlew to 4.1

### PR DESCRIPTION
**Pull request by passsy**
improves compatibily with Android Studio 3.0

Required upgrade of bintray plugin https://github.com/novoda/bintray-release/pull/115

### CODE REVIEW

**Comment by StefMa** [comment]
Gradle 4.2 just released.. Any reasons why using 4.1?

I would recommend to upgrade the bintray release in this PR as well...

**Comment by passsy** [comment]
Oh, thought it is still rc2. Time flies. I also upgraded the bintray plugin (and tested it)

**Comment by passsy** [comment]
I tried upgrading to 4.2 but it doesn't work. `provided` dependencies cannot be added to the dependencies due to [internal gradle changes](https://github.com/gradle/gradle/commit/edf19395391e4e866770ae688993cec79a921d5d). We have to wait for stable Android Studio 3.0 and a gradle plugin upgrade

**Comment by StefMa** [comment]
Travis is so easy :grinning:
Thanks 👍

**Pull request merged**
