### PR TITLE
Add project codestyles

### LINKED ISSUE #122: Put codestyle into ThirtyInch
Since we [open sourced](https://github.com/grandcentrix/androidcodestyle) our code style I think about to add it here.
We can add it together with a CONTRIBUTING.md ( 🤔 ) to Ti. We won't have conflicts or "rerange the code everytime" if third parties contribute anymore...

What do you think @passsy @rberghegger ❓

### PR DESCRIPTION
**Pull request by rberghegger**
This will fix #122 
As discussed in #122 this pull request adds project specific code styles based on the grandcentrix android code styles (https://github.com/grandcentrix/androidcodestyle) to the project.

### CODE REVIEW

**Comment by passsy** [comment]
Not sure if we should convert all sources within this PR or not 🤔

**Comment by rberghegger** [comment]
@passsy Good point. Was thinking about that as well. 🤔  But I wanted to wait for your and @StefMa opinions before actually applying those styles.

**Comment by StefMa** [comment]
Hmm.. Since we don't have that much PR I would suggest to do it. 👍

**Comment by passsy** [comment]
true, just do it. If there are conflicts we can solve them by applying the code style as well

**Comment by rberghegger** [comment]
Done. I've applied the new project codestyle to every module individually. Additionally I've added `CONTRIBUTING.md` which contains a few informations regarding the codestyle.

**Comment by StefMa** [comment]
I would suggest to remove the TK from the contribution file. Also start with a single # and use two for code style... 👍 rest lgtm

**Pull request merged**
